### ISSUE TITLE
Where to install this?

### ISSUE THREAD

**Issue by garemoko** [adlnet/edx-xapi-bridge#5]
Apologies if this is a silly question; I;m half way through installing OpenEdx and I guess the answer may become clear by the time I've got it fully installed. 

Where does the code for this bridge need to sit? Does it go in the OepnEdx folder somewhere?

**Comment by stevenvergenz** [comment]
First a disclaimer: this project is quite old, and at the time OpenEdX was evolving fast, so this may not work anymore. Let me know if that's the case.

It doesn't matter where you set up the bridge, as long as the running user can read the log file.

**Comment by garemoko** [comment]
Thanks. I guess i need to install this on the vagrant box where I installed edex
